CMakeLists.txt
src/Cpu_unix.cpp
src/Mem_unix.cpp
src/Platform_unix.cpp

Hi @xmrig,
Per your request, please review.

Some fixes to compile on FreeBSD

---

CMakeLists.txt

Add -DBUILD_STATIC=ON for static builds

---

src/crypto/randomx/jit_compiler_x86_static.S

Fix Mac OS X compilation

---

src/crypto/randomx/argon2_core.c
src/crypto/randomx/blake2_generator.cpp
src/crypto/randomx/blake2_generator.hpp
src/crypto/randomx/bytecode_machine.cpp
src/crypto/randomx/common.hpp
src/crypto/randomx/instruction.hpp
src/crypto/randomx/intrin_portable.h
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/superscalar.cpp

- RandomX updated to the latest version
- Hashrate improved by 0.5-1.5% depending on RandomX variant and CPU.

Updated and optimized RandomX

---

src/crypto/randomx/superscalar.cpp

Fix a possible out-of-bounds access in superscalar generator

Sync with latest RandomX code

---

src/backend/cuda/CudaThread.cpp
src/backend/cuda/CudaThread.h
src/backend/cuda/runners/CudaBaseRunner.cpp
src/backend/cuda/runners/CudaRxRunner.cpp
src/backend/cuda/runners/CudaRxRunner.h
src/backend/cuda/wrappers/CudaDevice.cpp
src/backend/cuda/wrappers/CudaLib.cpp
src/backend/cuda/wrappers/CudaLib.h

RandomX: added support for dataset on host

---

src/App.cpp
src/backend/common/Workers.cpp
src/backend/cpu/CpuWorker.cpp
src/crypto/randomx/aes_hash.cpp
src/crypto/randomx/aes_hash.hpp
src/crypto/randomx/intrin_portable.h
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/randomx/virtual_machine.cpp
src/crypto/randomx/virtual_machine.hpp

Intel JCC erratum fix and various other improvements, see more here: https://www.phoronix.com/scan.php?page=article&item=intel-jcc-microcode&num=1

RandomX fixes

---

src/backend/cpu/CpuWorker.cpp
src/crypto/randomx/asm/program_read_dataset_ryzen.inc
src/crypto/randomx/jit_compiler_a64.cpp
src/crypto/randomx/jit_compiler_a64.hpp
src/crypto/randomx/jit_compiler_fallback.hpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/jit_compiler_x86_static.S
src/crypto/randomx/jit_compiler_x86_static.asm
src/crypto/randomx/jit_compiler_x86_static.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/randomx/virtual_machine.hpp
src/crypto/randomx/vm_compiled.cpp
src/crypto/rx/RxVm.cpp
src/crypto/rx/RxVm.h
src/net/JobResults.cpp

Removed register dependency in dataset read, +0.8% speedup on average.

Optimized dataset read for Ryzen CPUs

---

src/crypto/rx/Rx_windows.cpp

Use unique service name for WinRing0 driver

---

src/backend/opencl/cl/cn/algorithm.cl
src/backend/opencl/runners/OclRxBaseRunner.cpp
src/crypto/common/Algorithm.cpp
src/crypto/common/Algorithm.h
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/rx/RxAlgo.cpp

For testing:
```
"algo": "rx/sfx",
"coin": null,
"url": "sfx.pool-pay.com:4025",
"user": "Safex5zmLUJ1svEg2a4uwrMd2PNCjAXHeP36cyKAv9dd4kKzi8p2mySfFdN6rNyD1Zh4HafPszctQYAykDJkHdhREFh43p1QWtG4T",
```

RandomSFX (Safex Cash variant) support

---

README.md

Monero already changed PoW on Nov 30, 2019

---

src/crypto/rx/RxConfig.cpp

As per https://github.com/xmrig/xmrig/issues/1433#issuecomment-572126184

Update MSR preset for Intel

---

scripts/randomx_boost.sh

#1493 change missed from script

add intel change to boost script

---

src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/AdvancedCpuInfo.cpp
src/backend/cpu/platform/BasicCpuInfo.cpp
src/crypto/rx/RxConfig.cpp
src/crypto/rx/Rx_linux.cpp
src/crypto/rx/Rx_win.cpp

Also fixed verbose output for MSR presets with masks.

MSR preset for Bulldozer CPUs

---

src/crypto/randomx/aes_hash.cpp
src/crypto/randomx/jit_compiler_a64.hpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/vm_compiled.cpp

0.3-0.4% speedup depending on CPU.

Tuned JIT compiler

---

src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp

Shorter version using BMI2 instructionns

Optimized CFROUND

---

src/backend/cpu/CpuWorker.cpp
src/backend/cpu/CpuWorker.h
src/crypto/randomx/blake2/blake2b.c
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.h
src/crypto/rx/RxVm.cpp
src/crypto/rx/RxVm.h
src/net/JobResults.cpp

- Smaller memory footprint
- A bit faster overall

RandomX JIT refactoring

---

src/base/io/json/Json.cpp
src/base/io/json/Json.h
src/base/io/json/JsonChain.cpp
src/base/io/json/Json_unix.cpp
src/base/io/json/Json_win.cpp

Show incorrect lines in config.json together with line number and position.

Improved JSON config error reporting

---

src/crypto/astrobwt/sha3_256_avx2.S

Stop linker from making stack executable

---

src/3rdparty/argon2/arch/x86_64/lib/argon2-avx512f.c

Disabled AVX-512F for Argon2

---

src/backend/cuda/CudaWorker.cpp
src/backend/cuda/CudaWorker.h
src/backend/opencl/OclWorker.cpp
src/backend/opencl/OclWorker.h
src/net/JobResults.cpp
src/net/JobResults.h

Useful information when one GPU in a rig is producing errors.

Show GPU # when compute error happens

---

src/3rdparty/libethash/ethash_internal.c
src/3rdparty/libethash/ethash_internal.h
src/crypto/kawpow/KPCache.cpp
src/crypto/kawpow/KPHash.cpp

- 2 times faster CPU share verification: 11 -> 5 ms, reduces latency when submitting shares to a pool
- Also 1.5 times faster light cache initialization

KawPow: optimized CPU share verification

---

src/crypto/rx/Rx_linux.cpp
src/crypto/rx/Rx_win.cpp

Make sure user knows that hashrate is worse than it could be.

Print error message when MSR mod fails

---

src/crypto/randomx/asm/program_read_dataset_ryzen.inc
src/crypto/randomx/randomx.h

RandomX: tweaked Ryzen code

---

src/base/kernel/Platform.h
src/base/kernel/Platform_mac.cpp
src/base/kernel/Platform_unix.cpp
src/base/kernel/Platform_win.cpp
src/base/kernel/config/BaseConfig.cpp
src/base/kernel/config/BaseConfig.h
src/config.json
src/core/Miner.cpp
src/core/config/Config.cpp
src/core/config/Config_default.h

True by default (mining on battery enabled).

Added mining on battery setting

---

src/crypto/randomx/aes_hash.cpp
src/crypto/randomx/aes_hash.hpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/soft_aes.cpp
src/crypto/randomx/soft_aes.h
src/crypto/randomx/virtual_machine.cpp
src/crypto/randomx/virtual_machine.hpp
src/crypto/randomx/vm_compiled.cpp
src/crypto/randomx/vm_compiled.hpp
src/crypto/randomx/vm_compiled_light.cpp
src/crypto/randomx/vm_compiled_light.hpp
src/crypto/randomx/vm_interpreted.cpp
src/crypto/randomx/vm_interpreted.hpp
src/crypto/randomx/vm_interpreted_light.cpp
src/crypto/randomx/vm_interpreted_light.hpp
src/crypto/rx/Rx.cpp

RandomX: returned old soft AES impl and auto-select between the two

---

src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/BasicCpuInfo.cpp
src/backend/cpu/platform/BasicCpuInfo.h
src/crypto/randomx/bytecode_machine.cpp
src/crypto/randomx/bytecode_machine.hpp
src/crypto/randomx/common.hpp
src/crypto/randomx/jit_compiler_a64.cpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h

Small x86 JIT compiler speedup.

RandomX refactoring, moved more stuff to compile time

---

src/crypto/randomx/aes_hash.cpp
src/crypto/randomx/soft_aes.cpp

- A bit faster hardware AES code when compiled with MSVC
- More reliable software AES benchmark

RandomX: AES improvements

---

src/backend/opencl/runners/OclKawPowRunner.cpp
src/backend/opencl/runners/OclKawPowRunner.h
src/backend/opencl/runners/tools/OclKawPow.cpp
src/backend/opencl/runners/tools/OclKawPow.h

KawPow: fixed OpenCL memory leak

---

src/crypto/randomx/aes_hash.cpp
src/crypto/randomx/aes_hash.hpp
src/crypto/randomx/soft_aes.cpp
src/crypto/randomx/soft_aes.h
src/crypto/randomx/virtual_machine.cpp
src/crypto/rx/Rx.cpp

Previously removed unrolled variant is faster on some CPUs
Some CPUs are faster with added unrolled variant
The best variant depends on number of threads on some CPUs

soft_aes: fix previous optimization

---

src/core/Miner.cpp
src/crypto/common/Nonce.cpp
src/crypto/common/Nonce.h

Remove unexpected resume due to disconnect during dataset init

Miner: fix state machine

---

src/backend/cpu/CpuConfig.cpp
src/backend/cpu/CpuConfig.h
src/config.json
src/core/config/Config_default.h
src/crypto/cn/CnCtx.cpp
src/crypto/cn/CnHash.cpp
src/crypto/common/MemoryPool.cpp
src/crypto/common/MemoryPool.h
src/crypto/common/VirtualMemory.h
src/crypto/common/VirtualMemory_unix.cpp
src/crypto/common/VirtualMemory_win.cpp
src/crypto/randomx/dataset.hpp
src/crypto/randomx/jit_compiler_a64.cpp
src/crypto/randomx/jit_compiler_a64.hpp
src/crypto/randomx/jit_compiler_fallback.hpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/randomx/virtual_memory.cpp
src/crypto/randomx/virtual_memory.hpp
src/crypto/randomx/vm_compiled.hpp
src/crypto/rx/Rx.cpp
src/crypto/rx/RxVm.cpp

Set to false by default, gives 0.2% boost on Ryzen 7 3700X with 16 threads, but hashrate might be unstable on Ryzen between launches. Use with caution.

RandomX: added `huge-pages-jit` config parameter

---

src/backend/common/Worker.cpp
src/backend/common/Worker.h
src/backend/common/Workers.cpp
src/backend/common/interfaces/IWorker.h

Use single atomic operation to switch between data points.

Fix possible race condition in hashrate counting code

---

src/crypto/rx/RxConfig.cpp

New MSR mod for Ryzen

---

src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/BasicCpuInfo.cpp
src/crypto/rx/RxConfig.cpp

Another +0.5% speedup for Zen2

Separate MSR mod for Zen/Zen2 and Zen3

---

src/crypto/randomx/jit_compiler_x86.cpp

Optimized JIT compiler

---

src/base/net/stratum/DaemonClient.cpp
src/base/tools/Cvt.cpp

Fixed solo mining

---

src/crypto/rx/Rx_linux.cpp
src/crypto/rx/Rx_win.cpp

Fixed pluralization/tense in a couple of error messages.

fixed grammar in a couple of awkward error messages

---

src/donate.h

Changed agaiin to again in line 37

Spelling Check in donate.h

---

src/base/kernel/Platform.h
src/base/kernel/Platform_unix.cpp
src/base/kernel/Platform_win.cpp
src/base/kernel/config/BaseConfig.cpp
src/base/kernel/config/BaseConfig.h
src/base/kernel/config/BaseTransform.cpp
src/base/kernel/interfaces/IConfig.h
src/config.json
src/core/Miner.cpp
src/core/config/Config.cpp
src/core/config/Config_default.h
src/core/config/Config_platform.h
src/core/config/usage.h

Windows only for now. When set to true, pauses mining when user touches mouse or keyboard.

Added `pause-on-active` option

---

src/base/net/stratum/DaemonClient.cpp
src/base/net/stratum/DaemonClient.h

Fix for https://github.com/xmrig/xmrig/issues/2127

Fixed many "new job" messages when solo mining

---

src/backend/cpu/CpuWorker.cpp

Fixes https://github.com/xmrig/xmrig/issues/2156

Fix crash in cn-heavy on Zen3 with manual thread count

---

src/base/net/stratum/NetworkState.cpp

Fixing mixed phrasing in error message

Minor verbiage tweak

---

src/base/tools/Handle.h

Bug found by Address Sanitizer

Fix wrong type in Handle::deleteLater()

---

src/backend/opencl/wrappers/AdlLib_linux.cpp

Suggested solution to bug https://github.com/xmrig/xmrig/issues/2171

Added reference to limits.h in AdlLib_linux.cpp

---

cmake/randomx.cmake
src/crypto/randomx/common.hpp
src/crypto/randomx/jit_compiler.hpp
src/crypto/randomx/randomx.cpp

Because RandomX JIT use asm code

Don't use RandomX JIT if WITH_ASM=OFF

---

src/crypto/cn/CryptoNight_x86.h

See https://github.com/xmrig/xmrig/issues/2232#issuecomment-812993963

Fixed cn-heavy for GCC-8

---

src/base/net/stratum/Client.cpp
src/base/net/stratum/DaemonClient.cpp
src/base/net/stratum/SelfSelectClient.cpp

Fixed broken "coin" setting functionality

---

src/backend/cpu/CpuBackend.cpp

Show total hashrate if compiled without OpenCL

---

src/crypto/cn/CnHash.cpp
src/crypto/cn/CryptoNight_x86.h
src/crypto/cn/asm/cn2/cnv2_upx_double_mainloop_zen3.inc
src/crypto/cn/asm/cn_main_loop.S
src/crypto/cn/asm/cn_main_loop.asm
src/crypto/cn/asm/win64/cn2/cnv2_upx_double_mainloop_zen3.inc
src/crypto/cn/asm/win64/cn_main_loop.S
src/crypto/cn/asm/win64/cn_main_loop.asm

- Optimized asm code for Zen3
- GCC has the same speed as MSVC now

Optimized cn/upx2

---

src/crypto/cn/asm/cn2/cnv2_upx_double_mainloop_zen3.inc
src/crypto/cn/asm/win64/cn2/cnv2_upx_double_mainloop_zen3.inc
src/crypto/common/HugePagesInfo.h

Also optimized cn/upx for Zen3, ~0.9% faster

Fixed rounding mode after running cn/upx

---

src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp

Fixed broken light mode mining on x86

---

src/crypto/randomx/asm/program_read_dataset_sshash_fin.inc
src/crypto/randomx/asm/program_read_dataset_sshash_init.inc
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h

Enabled IMUL_RCP optimization for light mode mining

---

src/crypto/randomx/asm/program_read_dataset_sshash_init.inc

RandomX: fix broken light mode mining

---

src/hw/msr/Msr_linux.cpp

Some custom linux kernel may be builtin msr, please support such case. Thanks.

support builtin msr

---

CHANGELOG.md
src/hw/msr/Msr_linux.cpp
src/version.h

Jsonboss patch 1

---

src/base/net/stratum/Job.cpp
src/base/net/stratum/Job.h
src/net/Network.cpp

Useful to check if pool/proxy is working properly and can also be used to compare different pools.

Show the number of transactions in pool job

---

src/base/crypto/Coin.cpp
src/base/crypto/Coin.h
src/base/kernel/interfaces/IClient.h
src/base/net/stratum/BaseClient.cpp
src/base/net/stratum/BaseClient.h
src/base/net/stratum/DaemonClient.cpp
src/base/net/stratum/DaemonClient.h
src/base/net/stratum/Pool.cpp
src/base/tools/cryptonote/BlobReader.h
src/base/tools/cryptonote/BlockTemplate.cpp
src/base/tools/cryptonote/BlockTemplate.h
src/base/tools/cryptonote/WalletAddress.cpp
src/base/tools/cryptonote/WalletAddress.h

Previously added wallet address parser now used to detect coin by user specified wallet address for daemon mining. That mean `coin` and `algo` option is not required for following coins:
- Monero
- Wownero
- Sumokoin 
- ArQmA
- Wownero
- DERO
List of coins may extend in future.

Added automatic coin detection for daemon mining

---

scripts/generate_cl.js
src/backend/opencl/cl/cn/algorithm.cl
src/backend/opencl/cl/rx/randomx.cl
src/backend/opencl/cl/rx/randomx_constants_graft.h
src/base/crypto/Algorithm.cpp
src/base/crypto/Algorithm.h
src/base/crypto/Coin.cpp
src/base/crypto/Coin.h
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/rx/RxAlgo.cpp

Added Graft RandonX

---

src/base/io/Env.cpp

Fixed Windows 7 compatibility

---

CMakeLists.txt
src/core/Miner.cpp
src/core/Taskbar.cpp
src/core/Taskbar.h

- Red when there's no connection to any pool
- Yellow when mining is paused
- No color during normal mining

Added Windows taskbar icon colors

---

src/backend/cpu/CpuWorker.cpp
src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/BasicCpuInfo.h

Fix: use cn-heavy optimization only for Vermeer CPUs

---

src/crypto/cn/CryptoNight_x86.h

Small speedup on desktop Zen2/Zen3 CPUs. Updated performance table:
CPU|cpuminer-gr-avx2 (tuned), h/s|XMRig (MSVC build), h/s|Speedup
-|-|-|-
AMD Ryzen 7 4700U|632.6|731|+15.5%
Intel Core i7-2600|496.4|533.6|+7.5%
AMD Ryzen 7 3700X @ 4.1 GHz|2453.0|2469.1|+0.65%
AMD Ryzen 5 5600X @ 4.65 GHz|2112.6|2221.2|+5.1%
Detailed results: https://imgur.com/a/GCjEWpl

Optimized quad hash for Ryzens

---

src/base/base.cmake
src/base/net/stratum/EthStratumClient.cpp
src/base/net/stratum/Pool.cpp

- Fixed "difficulty is not a number" when diff is high on some pools - #2737
- Fixed GhostRider compilation when WITH_KAWPOW=OFF

More GhostRider fixes

---

src/backend/cpu/platform/BasicCpuInfo.cpp
src/crypto/cn/CryptoNight_x86_vaes.cpp
src/crypto/ghostrider/ghostrider.cpp

VAES crash fixes

---

src/base/base.cmake
src/base/tools/Chrono.cpp
src/crypto/ghostrider/ghostrider.cpp
src/crypto/randomx/aes_hash.cpp

Refactored Chrono::highResolutionMSecs()

---

src/backend/cpu/CpuWorker.cpp
src/crypto/ghostrider/ghostrider.cpp
src/crypto/ghostrider/ghostrider.h

GhostRider: set correct priority for helper threads

---

src/base/net/stratum/Client.cpp
src/base/net/stratum/Client.h
src/base/net/stratum/Pool.h

Add support for client.reconnect method

---

src/crypto/ghostrider/ghostrider.cpp

Fixed GhostRider benchmark on single-core systems

---

src/crypto/ghostrider/ghostrider.cpp

Fixed GhostRider with hwloc disabled

---

src/backend/common/WorkerJob.h
src/backend/cpu/CpuWorker.h

Fixes for 32-bit ARM

---

src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp

4% more instructions removed than in #3119

RandomX: optimized CFROUND elimination more

---

src/backend/cpu/CpuWorker.cpp
src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/BasicCpuInfo.cpp
src/crypto/cn/CnHash.cpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/rx/RxConfig.cpp

RandomX: added MSR mod for Zen 4

---

src/crypto/cn/sse2neon.h

Maybe fixes #3143, until GCC 13 comes out of course.  Requires testing I did very little work at all since this will just be ignored anyway.

Update to latest sse2neon.h from github:DLTcollab/sse2neon

---

src/backend/cpu/platform/BasicCpuInfo_arm.cpp
src/base/kernel/Platform_unix.cpp
src/crypto/common/VirtualMemory_unix.cpp
src/hw/dmi/DmiReader_unix.cpp

Added ifdefs for DragonflyBSD

---

src/base/net/stratum/Client.cpp

Show IP address for failed connections

---

src/backend/cpu/CpuWorker.cpp
src/backend/cpu/CpuWorker.h

RandomX VMs didn't get updated properly in light mode.

Fixed broken RandomX light mode mining

---

src/backend/opencl/runners/tools/OclKawPow.cpp

`uv_queue_work` can't be called from other threads, only `uv_async_send` is thread-safe.
Closes #3287

KawPow: fixed data race when building programs

---

src/base/crypto/Coin.cpp
src/base/crypto/Coin.h
src/base/tools/cryptonote/BlockTemplate.cpp

Solo mining will require `--coin Zephyr` in command line, or `"coin": "Zephyr",` in `pools` section of config.json

Zephyr coin support

---

src/base/kernel/config/BaseConfig.cpp
src/version.h

To make it more clear what binary it is on some XMRig screenshot.

Add "built for OS/architecture/bits" to "ABOUT"

---

src/crypto/cn/sse2neon.h

Update to latest sse2neon.h

---

src/base/tools/cryptonote/BlockTemplate.cpp

Fixes `Invalid block template received from daemon.`

Updated pricing record size for Zephyr solo mining

---

src/base/io/log/FileLogWriter.cpp
src/base/io/log/FileLogWriter.h

Thread-safe FileLogWriter

---

src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/BasicCpuInfo.cpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/rx/RxConfig.cpp

Preliminary Zen5 support, MSR mod is not ready yet.

Added Zen5 detection

---

src/crypto/ghostrider/README.md

docs: update ghostrider/README.md

---

src/backend/cuda/runners/CudaRxRunner.cpp
src/backend/cuda/runners/CudaRxRunner.h
src/backend/cuda/wrappers/CudaLib.cpp
src/backend/cuda/wrappers/CudaLib.h

Fixes "GPU COMPUTE ERROR" after ~2 days of mining (when RandomX dataset changes).

CUDA backend: update RandomX dataset when it changes

---

src/backend/cpu/platform/HwlocCpuInfo.cpp

Hwloc: fixed detection of L2 cache size for some complex NUMA topologies
