src/crypto/soft_aes.h

Performance boost validated on Core 2 Quad processor under Windows 10.
But it's Windows/MS Visual C++ specific.

+15% boost on CryptoNight algo with non-AES CPU

---

src/crypto/CryptoNight.cpp
src/crypto/CryptoNight.h
src/crypto/CryptoNight_arm.h
src/crypto/CryptoNight_x86.h
src/workers/DoubleWorker.cpp
src/workers/SingleWorker.cpp

Changes for the monero version pow changes. Some implementation notes:
- The arm version needs to be tested.
- All versions access the scratchpad directly after the first tweak, instead of unpacking the simd register. The 11 byte needs to be manipulated, as you can see.
- All versions modify the 64-bit stack value instead of the scratchpad.
- A boolean template argument was added to remove branching from the aeon version.
- The version parameter isn't technically needed (the callee can get this from the input), but I decided to do this because all the other implementations were doing this - in case the miner is used for monero-like variants it can be configured at runtime. The penalty is setting up a register for the call.

Changes for the Monero v1 PoW

---

src/common/log/FileLog.cpp

Using option `--log-file` on non-seekable files such as pipe or tty, will fail; due to using offset `0` for `uv_fs_write(3)`. This patch fixed the bug by setting offset to `-1`, which is means don't change offset.

Fix FileLog (--log-file) fails on non-seekable files

---

src/common/Platform_mac.cpp

`Platform_mac.cpp` has used clang specific macros, making it impossible to be compiled by any other compilers.

Fix impossible to build for OS X without clang

---

CMakeLists.txt

FreeBSD needs the pthread linker flag.

FreeBSD needs pthread

---

src/common/Platform_unix.cpp

Currently it reports i686 on ARM.

Properly report ARM architecture on user agent.

---

src/crypto/cn_gpu_avx.cpp

Fix compilation with Clang 3.5 for those with limited compiler choices
Performance similar to gcc7+ on systems where gcc4 is the only alternative
Based on [official LLVM upstream patch](http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20150518/129343.html) that was merged sometime after 3.5.0

Fix compilation with Clang 3.5

---

README.md

minemonero.pro is deprecated, added new image for hashvault.pro on readme
https://imgur.com/a/b4pPCVc

updates image used in readme for new pool url

---

src/core/Config.cpp

to fix the following errors:
xmrig\src\core\Config.cpp(165): error C2065: 'max': undeclared identifier
xmrig\src\core\Config.cpp(165): error C2275: 'size_t': illegal use of this type as an expression

Config: fix std::max issue with msvc2017

---

cmake/flags.cmake
src/crypto/soft_aes.h

which now includes its own _rotr intrinsic, so the fill-in collided with some already-defined errors.

Repair compilation with Clang 9.0.0

---

src/crypto/randomx/virtual_machine.cpp

More bytes than needed were filled.

Correct buffer size for fillAes4Rx4

---

src/backend/cpu/platform/HwlocCpuInfo.cpp

Build hwloc version string based on HWLOC_API_VERSION, whenever `hwlocVersion` object does not exist (<1.11.x)
Probably could just use this method on all versions, as it is more important to display the compiled lib/header version, than whatever the XML tree says its version is (which could be different?).  Maybe complain if they mismatch?

Build hwloc version string based on HWLOC_API_VERSION

---

src/backend/cpu/CpuWorker.cpp

Thread could deadlock if it started before dataset struct was allocated.
Thanks to crCr62U0 for reporting this.

Fixed race condition in RandomX thread init

---

src/crypto/cn/asm/CryptonightR_template.S
src/crypto/cn/asm/cn_main_loop.S
src/crypto/cn/asm/win64/cn_main_loop.S
src/crypto/randomx/jit_compiler_x86_static.S

See: https://wiki.ubuntu.com/SecurityTeam/Roadmap/ExecutableStacks
See: https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart

Fix linker marking entire executable as having an executable stack

---

src/crypto/randomx/asm/program_loop_load.inc
src/crypto/randomx/asm/program_loop_store.inc
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/jit_compiler_x86_static.S
src/crypto/randomx/jit_compiler_x86_static.asm
src/crypto/randomx/jit_compiler_x86_static.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h

Prefetches scratchpad data as soon as possible to calculate data address for the next load.
Up to ~1.4% speedup on Ryzen 7 3700X @ 4.1 GHz, RAM 3200 MHz 14-14-14-28 with optimized sub-timings:
Variant|Before H/S|After H/S
-------|----------|-----------
rx/0|8663|8777
rx/wow|9867|10009
rx/loki|8652|8731

RandomX: optimized loading from scratchpad

---

src/crypto/randomx/jit_compiler_a64_static.S
src/crypto/randomx/virtual_machine.hpp

ldr/madd instruction sequence makes compiled binary crash (linker replaces madd with random jump instruction), so separate them.

Workaround for a bug in binutils-2.32-1 on ARM

---

src/backend/opencl/wrappers/OclDevice.cpp
src/backend/opencl/wrappers/OclDevice.h

This fixes random return of 0(zero) of globalMemSize() described in this issue https://github.com/xmrig/xmrig/issues/1235

Fixes OclDevice::globalMemSize() that sometimes returns 0

---

src/base/net/stratum/Client.h

This is needed for block templates over self-select as a block template can be over 2048 bytes. [[ref](https://github.com/jtgrassie/monero-pool/issues/28)]

increase stratum send buffer size

---

src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/jit_compiler_x86_static.S
src/crypto/randomx/jit_compiler_x86_static.asm

To avoid false dependencies on upper 128 bits of YMM registers.

Add vzeroupper for processors with AVX

---

src/backend/opencl/cl/cn/algorithm.cl
src/backend/opencl/cl/rx/randomx.cl
src/backend/opencl/cl/rx/randomx_constants_v.h
src/crypto/common/Algorithm.cpp
src/crypto/common/Algorithm.h
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/rx/RxAlgo.cpp

Latest code from MoneroOcean/xmrig master, only the MoneroV rx/v algorithm part, remastered only slightly (shifted some lines around for consistency)
Appears to also support opencl backend (no CUDA).

Add MoneroV (rx/v) algorithm [based on MoneroOcean/master]

---

src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/AdvancedCpuInfo.cpp
src/backend/cpu/platform/BasicCpuInfo.cpp
src/crypto/rx/RxConfig.cpp

It turned out to be useless: https://www.reddit.com/r/MoneroMining/comments/et7s7w/psa_amd_opteronfxa6a8a10_owners_needed_to_test/

Removed MSR mod for Bulldozer

---

src/base/kernel/Platform_hwloc.cpp
src/base/kernel/Platform_mac.cpp
src/base/kernel/Platform_unix.cpp
src/base/kernel/Platform_win.cpp

Added 1 ms sleep to guarantee thread rescheduling to the correct CPU core before returning.

Fixed setThreadAffinity()

---

src/backend/cpu/CpuBackend.cpp
src/backend/cpu/CpuConfig.cpp
src/backend/cpu/CpuConfig.h
src/backend/cpu/CpuLaunchData.cpp
src/backend/cpu/CpuLaunchData.h
src/backend/cpu/CpuWorker.cpp
src/backend/cpu/CpuWorker.h
src/config.json
src/core/config/Config_default.h
src/crypto/astrobwt/AstroBWT.cpp
src/crypto/astrobwt/AstroBWT.h

Skips hashes with large stage 2 size. Added configurable `astrobwt-max-size` parameter, default value is 550, min 400, max 1200, optimal value ranges from 500 to 600 depending on CPU.
- Intel CPUs get 20-25% speedup
- 1st- and 2nd-gen Ryzens get 30% speedup
- 3rd-gen Ryzens get up to 50% speedup

AstroBWT 20-50% speedup

---

cmake/astrobwt.cmake
src/backend/cpu/CpuConfig.cpp
src/backend/cpu/CpuConfig.h
src/backend/cpu/CpuLaunchData.cpp
src/backend/cpu/CpuLaunchData.h
src/backend/cpu/CpuWorker.cpp
src/backend/cpu/CpuWorker.h
src/core/Miner.cpp
src/crypto/astrobwt/AstroBWT.cpp
src/crypto/astrobwt/AstroBWT.h
src/crypto/astrobwt/sha3_256_avx2.S
src/crypto/astrobwt/sha3_256_avx2.asm
src/crypto/astrobwt/sha3_256_avx2.inc
src/crypto/astrobwt/sha3_256_keccakf1600_avx2.inc

Added "astrobwt-avx2" parameter in config.json, it's turned off ("false") by default.
4-5% speedup on CPUs with proper AVX2 support (AMD Ryzen starting with Zen2, Intel Core starting with Haswell).
There will be no speedup on the following CPUs:
- Intel Pentium/Celeron don't support AVX2
- AMD Zen/Zen+ have only half-speed AVX
GCC compiled version is faster without AVX2, MSVC compiled version is faster with AVX2

AVX2 optimized code for AstroBWT

---

src/backend/cpu/CpuWorker.cpp
src/crypto/randomx/configuration.h
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/randomx/vm_compiled.hpp
src/crypto/randomx/vm_compiled_light.hpp
src/crypto/randomx/vm_interpreted.hpp
src/crypto/randomx/vm_interpreted_light.hpp
src/crypto/rx/RxVm.cpp
src/crypto/rx/RxVm.h
src/net/JobResults.cpp

+0.5% speedup on Zen2 when the whole L3 cache is used (16 threads on 3700X/3800X, 32 threads on 3950X).

Pooled allocation of RandomX VMs

---

cmake/OpenSSL.cmake
src/backend/opencl/OclCache_win.cpp
src/crypto/rx/Rx_win.cpp

When cross-compiling on case sensitive systems, such as Linux, there will be errors.
Change cases of Windows include files and link library.

Fix Windows include files cases

---

src/crypto/cn/c_jh.c

- Fixed uninitialized `state->x` warning
- Fixed broken code with `-O3` or `-Ofast`

Fixed GCC 10.1 issues

---

src/backend/opencl/runners/OclKawPowRunner.cpp

Display driver could reset on GPUs with screen connected.

Fixed DAG initialization on slower AMD GPUs

---

src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/BasicCpuInfo.cpp
src/backend/cpu/platform/BasicCpuInfo.h
src/config.json
src/crypto/rx/Rx.cpp
src/crypto/rx/Rx.h
src/crypto/rx/RxConfig.cpp
src/crypto/rx/RxConfig.h
src/crypto/rx/Rx_linux.cpp
src/crypto/rx/Rx_win.cpp

False by default. If set to true, all non-mining CPU cores will not have access to L3 cache.

RandomX: added cache QoS support

---

src/base/net/stratum/Job.h

Haven offshore now requires a **pricing_record** struct (size 192 bytes) to be present in the block_header. Therefore the blob size for a block_header has increased significantly.
This pull request increases the max supported blob size to 384 bytes - the first multiple of 96 above the required size for Haven offshore.

Increased max blob size to support Haven offshore capability

---

src/backend/cpu/CpuWorker.cpp
src/crypto/common/VirtualMemory.cpp
src/crypto/common/VirtualMemory.h
src/crypto/common/VirtualMemory_unix.cpp
src/crypto/rx/RxDataset.cpp
src/crypto/rx/RxDataset.h

- Don't allocate 1 GB per thread if 1 GB is default huge page size.
- Try to allocate scratchpad from dataset's 1 GB huge pages, if normal huge pages are not available

More robust 1 GB pages handling

---

src/base/net/stratum/Job.h

In self-select mode, we only have pool wallet right after login. Thanks to @cohcho for pointing this out.

Fixed self-select login sequence

---

cmake/OpenSSL.cmake

OpenSSL still links as shared library even if BUILD_STATIC=ON is provided.

Fix OpenSSL static link when BUILD_STATIC=ON is provided

---

src/config.json
src/core/config/Config_default.h
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h
src/crypto/rx/Rx.cpp
src/crypto/rx/RxConfig.cpp
src/crypto/rx/RxConfig.h

`scratchpad_prefetch_mode` can have 4 values:
0: off
1: use `prefetcht0` instruction (default, same as previous XMRig versions)
2: use `prefetchnta` instruction (faster on Coffee Lake and a few other CPUs)
3: use `mov` instruction

RandomX: added parameter for scratchpad prefetch mode

---

src/backend/common/WorkerJob.h
src/crypto/common/Nonce.cpp
src/crypto/common/Nonce.h

```
std::mutex replaced with std::atomic<uint64_t>::fetch_add
correct nonce iteration for the following cases:
uint32_t, with_nicehash:
[0 - 0xFFFFFF]
uint32_t, without_nicehash:
[0 - 0xFFFFFFFF]
uint64_t, without_nicehash:
[0 - 0x7FFFFFFFFFFFFFFF]
hashrate difference in practise for rx/0 on 4 cores Intel CPU:
>>> '{:.2f}%'.format((1907.8 - 1904.9) / 1904.9 * 100)
'0.15%'
```
https://github.com/cohcho/xmrig/commits/nonce_iteration
<details><summary>shell code for detailed perforamance comparison</summary>
```
%:commits=(nonce_iteration~2 nonce_iteration)
for commit in ${commits}; do;
git checkout --detach -f $commit
echo "\nCOMMIT:$commit:$(git rev-parse $commit)"
b=release;
B=build/$(git rev-parse HEAD)/$b;
rm -fr $B
cmake --log-level=ERROR -S . -B $B -GNinja …
```

nonce iteration optimization

---

src/backend/common/WorkerJob.h
src/base/net/stratum/Job.h
src/crypto/common/Nonce.cpp

Add Job::nonceMask() to know mutable bits
Reserve at most 1 bit within Nonce::next to detect counter wrapping

reserve at most 1 bit for wrapping detection

---

src/base/tools/Profiler.cpp
src/base/tools/Profiler.h
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp

JIT compilator was slower compared to MSVC compiled binary. Up to +0.1% speedup on rx/wow in Linux.

RandomX improved performance of GCC compiled binaries

---

src/crypto/randomx/aes_hash.cpp

the best order of hash/fill/prefetch depends on hw/soft AES
only hw AES is faster after previous optimization

soft_aes: fix previous optimization

---

src/crypto/randomx/aes_hash.cpp

Unrolled loop was 5-10% slower depending on CPU.

RandomX: optimized soft AES code

---

CMakeLists.txt
cmake/randomx.cmake
doc/build/CMAKE_OPTIONS.md

- Fixes #1844 by not using -msse4.1 on Blake2 when the target arch is ARM.
- `WITH_SSE` Cmake option added, one can disable SSE individually
- Same as #1860, just with a new `WITH_SSE` option. Pick one PR and close the other I guess :) (or whatever)

Fix ARM build - Blake2 without SSE, WITH_SSE cmake option

---

src/crypto/rx/RxVm.cpp

randomx_create_vm requires either cache or dataset, but not both

RxVm: fix randomx_create_vm call

---

src/backend/cpu/CpuWorker.cpp
src/backend/cpu/CpuWorker.h
src/crypto/randomx/aes_hash.cpp
src/net/JobResults.cpp

tempHash/output must be 16-byte aligned for randomx_calculate_hash{,_first,_next}

RandomX: align args

---

src/backend/common/Hashrate.cpp
src/backend/common/HashrateInterpolator.cpp
src/backend/common/HashrateInterpolator.h
src/backend/common/Worker.cpp
src/backend/common/Worker.h
src/backend/common/Workers.cpp
src/backend/common/common.cmake
src/backend/cpu/CpuBackend.cpp
src/backend/cpu/CpuWorker.cpp
src/backend/cuda/CudaBackend.cpp
src/backend/cuda/CudaWorker.cpp
src/backend/cuda/CudaWorker.h
src/backend/opencl/OclBackend.cpp
src/backend/opencl/OclWorker.cpp
src/backend/opencl/OclWorker.h
src/core/Miner.cpp

- Use only steady timestamp counters to guarantee correctness
- CPU backend: directly measure total hashrate using raw hash counters from each thread; update data more often on ARM CPUs because they're slower
- GPU backends: directly measure total hashrate too, but use interpolator with 4 second lag to fix variance from batches of hashes
Total hashrate is now measured directly (realtime for CPU, 4 seconds lag for GPU), so it might differ a bit from the sum of all thread hashrates because data points are taken at different moments in time.
Overhead is reduced a lot since it doesn't have to go through all threads to calculate max total hashrate on every timer tick (2 times a second).

More precise hashrate calculation

---

src/backend/common/Workers.cpp

Don't add data points where one of the threads doesn't have hashrate data yet.

Fixed total hashrate update

---

src/base/base.cmake
src/base/io/Async.cpp
src/base/io/Async.h
src/crypto/rx/RxQueue.h
src/net/JobResults.cpp

unix implementation of uv_async_t has been wasting cpu cycles for nothing since 1.29.0 release
implement efficient callback scheduling for linux

uv: fix performance issue

---

src/backend/cuda/CudaWorker.cpp
src/backend/opencl/OclWorker.cpp
src/backend/opencl/OclWorker.h

WorkerJob::nextRound() doesn't require roundSize to be power of 2
Use CudaWorker::intensity(), OclWorker::intensity() to get device batch size
Sync nonce and device iteration

WorkerJob: fix calls of add/nextRound

---

src/crypto/rx/Rx_linux.cpp

https://github.com/torvalds/linux/commit/a7e1f67ed29f0c339e2aa7483d13b085127566ab#diff-2f768554951616110618f5c2f6b3a580b570ca63a9bbbe6b3300adf66ee84443
Writes can still be allowed by supplying the `allow_writes=on` module parameter

MSR: supress kernel module warning

---

src/base/kernel/Base.cpp

Check for configuration files in the home directory to give the user sane config locations without a command line argument. Especially useful for Linux packaging. Made to resolve #1923

Add checking for config files in user home directory

---

src/backend/common/Benchmark.cpp
src/backend/common/interfaces/IWorker.h
src/backend/cpu/CpuBackend.cpp
src/backend/cpu/CpuWorker.cpp
src/backend/cpu/CpuWorker.h
src/backend/cuda/CudaBackend.cpp
src/backend/cuda/CudaWorker.cpp
src/backend/cuda/CudaWorker.h
src/backend/opencl/OclBackend.cpp
src/backend/opencl/OclWorker.cpp
src/backend/opencl/OclWorker.h
src/crypto/randomx/jit_compiler_x86.cpp

Each hash is dependent on the previous hash to make multi-threaded cheating impossible.

Make single thread bench cheat-resistant

---

src/Summary.cpp
src/backend/cpu/interfaces/ICpuInfo.h
src/backend/cpu/platform/BasicCpuInfo.cpp
src/backend/cpu/platform/BasicCpuInfo_arm.cpp

`x64` is short for `x86-64`, which only refers to this specific architecture made by AMD; using the term for any other 64-bit architectures such as `arm64` is wrong. Please simply use `64-bit` to indicate a 64-bit architecture.
Source file `src/backend/cpu/platform/BasicCpuInfo_arm.cpp` would still output JSON that uses `x64` to indicate 64-bit support, should it be fixed as well?

Don't use team 'x64' for '64-bit'

---

src/base/net/tools/MemPool.h

Currently fails with `error: 'size_t' was not declared in this scope;`, should everything be moved to `std::size_t`?

Fix build on GCC 11

---

.gitignore

Since [build docs](https://xmrig.com/docs/miner/build/ubuntu) mentions `scripts/build_deps.sh` it's output should be added into `.gitignore`
```bash
sudo apt install -y git build-essential cmake automake libtool autoconf
git clone --depth=1 https://github.com/xmrig/xmrig.git && cd xmrig
mkdir -p build && cd scripts
./build_deps.sh && cd ../build
cd ..
LANG=en_US git status
```
```
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
build/
deps/
nothing added to commit but untracked files present (use "git add" to track)
```

Added scripts/{build, deps} into .gitignore

---

src/hw/dmi/DmiReader_unix.cpp

Compilation fails if the above library is missing. This fixes a compilation error.

Add missing "cstdio" library

---

src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86_static.S
src/crypto/randomx/jit_compiler_x86_static.asm

Adopted from https://github.com/tevador/RandomX/pull/201

RandomX JIT x86: remove unnecessary instructions

---

src/backend/cpu/CpuConfig.cpp
src/backend/cpu/CpuConfig.h
src/base/kernel/interfaces/IConfig.h
src/core/Controller.cpp
src/core/config/ConfigTransform.cpp
src/core/config/Config_platform.h
src/core/config/usage.h
src/crypto/common/HugePagesInfo.cpp
src/crypto/common/HugePagesInfo.h
src/crypto/common/LinuxMemory.cpp
src/crypto/common/LinuxMemory.h
src/crypto/common/VirtualMemory.cpp
src/crypto/common/VirtualMemory.h
src/crypto/common/VirtualMemory_unix.cpp
src/crypto/common/VirtualMemory_win.cpp

This PR adds support for user configurable huge page sizes on Linux where huge pages with size other than 2 MB are supported. For example #2060 right now Linux on Apple M1 supports only 32 MB hugepages and doesn't support widely supported 2 MB huge pages. Also 32 MB and 64 kB huge pages can be tested on modern Amazon ARM instances with Neoverse N1 CPU (`*6g.*`)
Config option `"huge-pages"` extended, now it accepts huge pages size in kB, not only boolean value.
Examples:
- `"huge-pages": 2048,` this equal to `"huge-pages": true` default value for 2 MB huge pages.
- `"huge-pages": 32768,` - 32 MB huge pages.
- `"huge-pages": 64,` - 64 kB huge pages.
For command line usage added option `--hugepage-size`. 1 GB pages is not a valid option, since they are already supported in a special way. …

Added support for flexible huge page sizes on Linux.

---

src/backend/cpu/CpuBackend.cpp
src/backend/cpu/CpuConfig.cpp
src/backend/cpu/CpuWorker.cpp
src/backend/cpu/platform/HwlocCpuInfo.cpp
src/crypto/cn/CnHash.cpp
src/crypto/cn/CryptoNight_arm.h
src/crypto/cn/CryptoNight_x86.h
src/crypto/rx/Rx.cpp

- Uses scratchpad interleaving to access only the closest L3 slice from each CPU core.
- Also activates MSR mod for cn-heavy because CPU prefetchers get confused with interleaving
- 7-8% speedup on Zen3

Optimized cn-heavy for Zen3

---

src/crypto/cn/sse2neon.h

A few days after [this header was introduced](https://github.com/xmrig/xmrig/commit/b665d2d865efc04998b21a6c54f9ad56622f4872). Upstream updated it with [armv7 versions of `_mm_aesenc_si128`](https://github.com/DLTcollab/sse2neon/commit/3e384f7246ac1a26997f4663e64573b29fc72f5e) which allows xmrig to build on armv7.
This commit updates sse2neon.h to the current master, which is [this commit.](https://github.com/DLTcollab/sse2neon/commit/f8d829e8e8739445cedcc259bf840641bc7addbf)

Update sse2neon.h to the latest master. Fixes build on armv7.

---

doc/CPU.md

Userspace MSR writes are no longer allowed by default in Linux Kernels starting with 5.9. _(Per this [commit](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/misc&id=a7e1f67ed29f0c339e2aa7483d13b085127566ab) and [explaination](https://www.phoronix.com/scan.php?page=news_item&px=Linux-Filter-Tightening-MSRs).)_
Userspace MSR writes in kernels that are locked down by default can still be enabled if the `msr.allow_writes=on` kernel flag is set. I.e. setting  `GRUB_CMDLINE_LINUX_DEFAULT="msr.allow_writes=on"` in `/etc/default/grub` for most linux distros.

Added Userspace MSR permissions clarification in CPU.md

---

src/base/base.cmake
src/base/kernel/config/BaseConfig.cpp
src/base/kernel/config/BaseTransform.cpp
src/base/kernel/interfaces/IConfig.h
src/base/kernel/interfaces/IDnsBackend.h
src/base/kernel/interfaces/IDnsListener.h
src/base/net/dns/Dns.cpp
src/base/net/dns/Dns.h
src/base/net/dns/DnsConfig.cpp
src/base/net/dns/DnsConfig.h
src/base/net/dns/DnsRecord.cpp
src/base/net/dns/DnsRecord.h
src/base/net/dns/DnsRecords.cpp
src/base/net/dns/DnsRecords.h
src/base/net/dns/DnsRequest.h
src/base/net/dns/DnsUvBackend.cpp
src/base/net/dns/DnsUvBackend.h
src/base/net/http/HttpClient.cpp
src/base/net/http/HttpClient.h
src/base/net/stratum/Client.cpp
src/base/net/stratum/Client.h
src/base/net/stratum/benchmark/BenchClient.cpp
src/base/net/stratum/benchmark/BenchClient.h
src/core/config/Config.cpp
src/core/config/Config_platform.h
src/core/config/usage.h

* Added internal DNS cache with configurable TTL. `"ttl"` in `"dns"` object or `--dns-ipv6`.
* Added a new option to prefer to use IPv6. `"ipv6"` in `"dns"` object or `--dns-ttl=N`.
* General code improvements.

Improved DNS subsystem

---

src/crypto/cn/CryptoNight_x86.h

- Remove unnecessary type conversion when doing `idx0 = d ^ q;`
- Saves 1 CPU cycle in the main loop
- 0.2% speedup on Ryzen 5 5600X, results on other CPUs may vary

Optimized cn-heavy

---

src/crypto/cn/CryptoNight_x86.h

+0.7% in GCC builds, but GCC is still slower than MSVC on cn-heavy.

Optimize cn-heavy in GCC builds

---

src/backend/common/Workers.h

`memory` header ends up not being included when built without OpenCL support.
Closes: https://github.com/xmrig/xmrig/issues/2224

Add missing include

---

src/crypto/cn/CryptoNight_monero.h

when I read monero code, I found VARIANT4_RANDOM_MATH_INIT is different
this is monero:
```
#define VARIANT4_RANDOM_MATH_INIT() \
v4_reg r[9]; \
struct V4_Instruction code[NUM_INSTRUCTIONS_MAX + 1]; \
int jit = use_v4_jit(); \
do if (variant >= 4) \
{ \
for (int i = 0; i < 4; ++i) \
V4_REG_LOAD(r + i, (uint8_t*)(state.hs.w + 12) + sizeof(v4_reg) * i); \
v4_random_math_init(code, height); \
if (jit) \
{ \
int ret = v4_generate_JIT_code(code, hp_jitfunc, 4096); \
if (ret < 0) \
local_abort("Error generating CryptonightR code"); \
} \
} while (0)
```
this is xmrig:
```
#define VARIANT4_RANDOM_MATH_INIT(part) \
uint32_t r##part[9]; \
struct V4_Instruction code##part[256]; \
if (props.isR()) { \
r##part[0] = static_cast<uint32_t>(h##part[12]); \
r##part[1] = static_cast<uint32_t>(h##part[12] …
```

remove useless v4_random_math_init if algo is not cn/r

---

src/base/io/log/FileLogWriter.cpp
src/base/io/log/FileLogWriter.h

when build on some old gcc version, such as 9.3.0, is will failed with
`
FileLogWriter.h:34:41: error: array used as initializer
`

fix build error on gcc 4.8.5

---

src/crypto/cn/CryptoNight_x86.h
src/crypto/cn/asm/cn2/cnv2_upx_double_mainloop_zen3.inc
src/crypto/cn/asm/win64/cn2/cnv2_upx_double_mainloop_zen3.inc

- Invalid rounding mode was used which caused rejected shares sometimes
- Also optimized CN implode/explode functions a bit.

Fixed Zen3 asm for cn/upx2

---

src/backend/cuda/wrappers/CudaLib.cpp

Default loader for cuda backend on MacOS was `/System/Library/Frameworks/OpenCL.framework/OpenCL` and has been corrected to match recent MacOS fix for xmrig-cuda.  Copying `libxmrig-cuda.dylib` along side the xmrig executable and `loader: null` works perfectly.

Fixup MacOS CUDA backend default loader name

---

src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86_static.S
src/crypto/randomx/jit_compiler_x86_static.asm
src/crypto/randomx/jit_compiler_x86_static.hpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h

Saves 1 instruction and 1 byte in the main loop.

RandomX: added BMI2 version for scratchpad prefetch

---

src/crypto/randomx/jit_compiler_a64_static.S

Break dependency from readReg2 and readReg3. It should run faster on superscalar and out-of-order CPUs i.e. Apple M1.

RandomX ARMv8: optimized dataset read

---

scripts/randomx_boost.sh

Checked using www.shellcheck.net
Specific issues addessed:
* https://github.com/koalaman/shellcheck/wiki/SC2002
* Use POSIX instead of bash for wider compatibility
* Fail on error

Fix shellcheck warnings in randomx_boost.sh

---

src/base/base.cmake
src/base/kernel/config/BaseTransform.cpp
src/base/kernel/interfaces/IConfig.h
src/base/net/stratum/DaemonClient.cpp
src/base/net/stratum/DaemonClient.h
src/base/net/stratum/Pool.cpp
src/base/net/stratum/Pool.h
src/base/tools/bswap_64.h
src/base/tools/cryptonote/BlockTemplate.cpp
src/core/config/Config_platform.h
src/crypto/astrobwt/AstroBWT.cpp
src/net/Network.cpp

Gets new blocks from daemon immediately without polling, saving ~0.5 seconds on average when daemon gets new block from the network. Also saves some CPU cycles because it doesn't need to poll daemon every second.
Testing: add "daemon-zmq-port": 28083 to xmrig's pool config in config.json and run ./monerod --testnet --zmq-pub tcp://127.0.0.1:28083

ZeroMQ support for solo mining

---

src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/randomx.cpp
src/crypto/randomx/randomx.h

Nitpicks with no functional difference:
* Typo in `Progam` / `codeShh`, and one indent fix
* Some references were `snake_case` while the majority are `CamelCase`
* Some references didn't match the actual ASM `snake_case` label

Fixup RandomX naming consistency

---

src/backend/cpu/CpuWorker.cpp

Some compilers seem to have `-Werror` by default (clang-14?) and this warning caused compilation crash if `WITH_RANDOMX` is off.  Move definition of `miner_signature_ptr` to within the `#ifdef XMRIG_ALGO_RANDOMX` block.
```
/usr/src/xmrig/src/backend/cpu/CpuWorker.cpp: In instantiation of ‘void xmrig::CpuWorker<N>::start() [with long unsigned int N = 1]’:
/usr/src/xmrig/src/backend/cpu/CpuWorker.cpp:481:16:   required from here
/usr/src/xmrig/src/backend/cpu/CpuWorker.cpp:277:22: warning: unused variable ‘miner_signature_ptr’ [-Wunused-variable]
277 |             uint8_t* miner_signature_ptr = m_job.blob() + m_job.nonceOffset() + m_job.nonceSize();
|                      ^~~~~~~~~~~~~~~~~~~
/usr/src/xmrig/src/backend/cpu/CpuWorker.cpp: In instantiation of ‘void …
```

Fix compile warning/crash when WITH_RANDOMX=OFF

---

src/core/config/ConfigTransform.cpp

When generating a catch-all Asterisk thread profile for CPU backend, it enables kawpow.
Fix is to generate a `kawpow:false` to negate the catch-all and ensure kawpow is always deeply disabled for CPU.

Fix --threads generates "*" profile without "kawpow":false to negate it.

---

src/base/net/stratum/SelfSelectClient.cpp
src/base/tools/cryptonote/BlockTemplate.cpp
src/base/tools/cryptonote/BlockTemplate.h

This PR expands the parsing of the block template to include the merge mining tag.
Currently if the merged mining tag is present in the template it will fail to be parsed even though it is a valid tag.
Additionally the changes to SelfSelectClient.cpp appears to reduce the frequency of this issue:
https://github.com/xmrig/xmrig/issues/2609

fix: expand validation of tx_extra for merge mining tag

---

src/hw/msr/Msr_win.cpp

When WinRing0 driver starts, but some other version already created `\\.\WinRing0_1_2_0`, it returns error 183 ERROR_ALREADY_EXISTS - "Cannot create a file when that file already exists."

MSR mod: fix for error 183

---

src/base/kernel/interfaces/IConfig.h
src/base/net/stratum/benchmark/BenchClient.cpp
src/base/net/stratum/benchmark/BenchConfig.cpp
src/base/net/stratum/benchmark/BenchConfig.h
src/core/config/ConfigTransform.cpp
src/core/config/Config_platform.h

Command line:
```
./xmrig --bench=250K -a gr --rotation 15
```
Where `rotation` is an integer between 0 and 19 (inclusive) - GhostRider has 20 different combinations of algorithms that have different hashrates.

Benchmark support for GhostRider (offline only)

---

src/core/Miner.cpp

Was benchmarking GhostRider simultaneous to RandomX init, probably unintended and inaccurate

Only initGhostRider() when job is in the family

---

src/backend/common/Hashrate.cpp
src/backend/common/Hashrate.h
src/backend/common/Worker.h
src/backend/common/interfaces/IWorker.h
src/backend/cpu/CpuBackend.cpp
src/backend/cpu/CpuLaunchData.cpp
src/backend/cpu/CpuWorker.h
src/base/crypto/Algorithm.h
src/core/Miner.cpp
src/crypto/ghostrider/README.md

- Added average hashrate display
- Fixed the number of threads shown at startup
- Fixed `--threads` or `-t` command line option (but `--cpu-max-threads-hint` is recommended to use)

GhostRider hotfixes

---

src/crypto/cn/CryptoNight_x86_vaes.cpp

Stubs for missing intrinsics
Attempting to figure out the actual line, but for now 10.0.0 seems fine.  Tested with 10.3.0... might still be missing in between 9.3.0 and 10.3.0 somewhere.  Could be a more robust way to detect the missing functions directly, and not use versions at all...

Fix compile for VAES support with GCC<10

---

scripts/rtm_ghostrider_example.cmd
src/crypto/ghostrider/README.md

Added examples for SSL port command line that don't use #1 pool.

Updated GhostRider documentation

---

src/backend/cpu/CpuWorker.cpp
src/core/Miner.cpp
src/crypto/rx/RxQueue.cpp

It helps to not loose huge pages when the seed changes (every 2048 blocks, ~2.8 days).

RandomX: don't restart mining threads when the seed changes

---

src/crypto/cn/sse2neon.h

Compilation fails for armv7 on gcc 11, and updating the version in that line fixes it.

armv7 compilation fix

---

src/backend/opencl/runners/tools/OclKawPow.cpp

Fixes #2890: uv_default_loop() can't be used there because UV loops are not thread safe.

KawPow OpenCL: use separate UV loop for building programs

---

src/version.h

19.30+ is MSVC/2022 -- this fixes compiler info in version strings

Add MSVC/2022 to version.h

---

src/base/crypto/keccak.cpp

Big astrobwt/v2 speedup on non-AVX2 CPUs: **Core i7-2600 +64% (17 -> 28 kh/s)**

Optimized keccak

---

CMakeLists.txt

`set(CMAKE_CXX_STANDARD 11)` only works properly starting from cmake 3.1, see #3174

Update cmake required version to 3.1

---

src/base/kernel/config/BaseTransform.cpp
src/base/kernel/interfaces/IConfig.h
src/base/net/stratum/DaemonClient.cpp
src/base/net/stratum/DaemonClient.h
src/base/net/stratum/Pool.cpp
src/base/net/stratum/Pool.h
src/core/config/Config_platform.h
src/core/config/usage.h

It's important to update jobs frequently to get new transactions into the block template. See https://rucknium.me/posts/monero-pool-transaction-delay/ for more details.

Solo mining: added job timeout (default is 15 seconds)

---

src/crypto/cn/CryptoNight_x86.h

Don't define `_mm_cvtsi128_si64` and `_mm_cvtsi64_si128` because clang 15 already has them in its headers.

Fix for 32-bit clang 15

---

src/backend/opencl/runners/OclBaseRunner.cpp
src/backend/opencl/runners/OclCnRunner.cpp
src/backend/opencl/runners/OclKawPowRunner.cpp
src/backend/opencl/runners/OclRxJitRunner.cpp
src/base/net/http/HttpResponse.h

Now some header files are not included transistively with new libstdc++.
Bug: https://bugs.gentoo.org/895226

Fix build with gcc 13

---

src/base/net/stratum/DaemonClient.cpp
src/base/net/stratum/DaemonClient.h

If the caller knows the difficulty of a PoW hash a given nonce yields, it can tell the callee via the X-Hash-Difficulty, which may allow the callee to skip some processing if the difficulty does not meet some criterion.
In my case, a merge mining proxy can know it's pointless trying to submit the nonce to a chain with higher difficulty when the nonce only meets the difficulty for a lower difficulty chain.

DaemonClient: new X-Hash-Difficulty HTTP header optimization

---

scripts/benchmark_10M.cmd
scripts/benchmark_1M.cmd
scripts/pool_mine_example.cmd
scripts/rtm_ghostrider_example.cmd
scripts/solo_mine_example.cmd

This is a re-do of what was #3239 but against `dev` branch.
When using a shortcut on C: drive that points to an xmrig script on another drive (ex. D:), and the shortcut is run as Administrator, the resulting script reports xmrig.exe not found.
- Shortcut file: `C:\Users\name\Desktop\xmrig.lnk`
- "Target" field in the shortcut points to `D:\xmrig\benchmark_1M.cmd`
- Right-click on desktop shortcut, choose Run as administrator
- Result: `'xmrig.exe' is not recognized as an internal or external command, operable program or batch file.`
As of Windows 10 (possibly 8), you cannot work around this problem using the "Start in" field of shortcuts; it isn't honoured when things are run as Administrator.  This is intentional on Microsoft's part, citing some security-related concern.  Debating this …

Improve .cmd files when run by shortcuts on another drive

---

src/backend/cpu/platform/HwlocCpuInfo.cpp

Alder Lake and newer CPUs have exclusive L3 cache and benefit from more threads until L3+L2 is filled.

Tweaked auto-tuning for Intel CPUs

---

src/crypto/randomx/aes_hash.cpp

Using an inactive member of a `union` is an undefined behavior in C++

RandomX: fixed undefined behavior

---

scripts/pool_mine_example.cmd
scripts/solo_mine_example.cmd

- Hashvault is top 1 pool now, so changed it to a smaller pool
- node.xmr.to doesn't exist anymore

Updated example scripts

---

src/backend/cuda/wrappers/CudaLib.cpp

Right now if provided cuda loader fails to load on linux it wouldn't show error, instead log  `CUDA: disabled ((null))`

fix(cuda): receive CUDA loader error on linux too.

---

README.md

Sorry to create a second PR, but I didn't catch this last time. XMRig also supports 32 bit x86, which I just tested, so I'm adding that to the README.

Add x86 to README

---

src/base/net/stratum/Client.cpp
src/base/net/stratum/Pool.cpp
src/base/net/stratum/Pool.h
src/base/net/stratum/Tls.cpp
src/base/net/stratum/Tls.h

Disabled by default, add `"sni": true,` to pool config to enable it.

Added SNI option for TLS connections

---

src/base/crypto/Coin.cpp
src/base/crypto/Coin.h
src/base/tools/cryptonote/BlockTemplate.cpp
src/base/tools/cryptonote/WalletAddress.cpp

xmrig is unable to mine townforge due to failing address validation.
Maybe it should leave this to the daemon, which surely knows better.

add support for townforge (monero fork using randomx)

---

src/base/api/Api.cpp

Previously with HTTP API enabled on brenchmarking run, it is possible to cause a segfault due to an issue handling the m_httpd pointer and rebinding.
- Initialize m_httpd to nullptr to indicate when it's not in use.
- Safely delete m_httpd in Api's destructor to prevent use-after-free issues.
- Add checks to ensure m_httpd is not nullptr before usage in start, stop, and tick methods.
- Log errors for HTTP server start failures to aid in debugging.
Fixes MoneroOcean/xmrig#120

Fix segfault in HTTP API rebind

---

src/crypto/randomx/jit_compiler_a64.cpp
src/crypto/randomx/jit_compiler_a64.hpp
src/crypto/randomx/jit_compiler_x86.cpp
src/crypto/randomx/jit_compiler_x86.hpp
src/crypto/randomx/randomx.cpp

No buffer overflow, better fix for `_FORTIFY_SOURCE`. Replaces #3450 and #3461.

RandomX: correct memcpy size for JIT initialization

---

src/base/io/json/Json.cpp

Rounding a regular FP value can give an invalid result - check the result too.

Make Json::normalize more strict

---

src/backend/cpu/CpuWorker.cpp
src/backend/cuda/CudaWorker.cpp
src/backend/opencl/OclWorker.cpp
src/core/Miner.cpp

Also never get a new job when mining is paused.
Possible fix for #3404

Always reset nonce on RandomX dataset change

---

src/backend/cpu/platform/HwlocCpuInfo.cpp

The code in the `if` block was originally added as a special case for some Intel CPUs. Zen5 has 16-way associative L2 cache, so this code started triggering and reduced the auto-generated number of threads by 50%.

Fixed threads auto-config on Zen5

---

src/backend/cpu/platform/HwlocCpuInfo.cpp

Before: https://xmrig.com/benchmark/6LiHex (6897 h/s)
After: https://xmrig.com/benchmark/2TG82a (7504 h/s)

Optimized autoconfig for AMD CPUs with < 2 MB L3 cache per thread

---

src/base/net/https/HttpsClient.cpp

- Don't write empty buffers
- Don't write if an error was returned

Fixed HttpsClient::flush logic

---

src/base/kernel/config/BaseTransform.cpp
src/base/kernel/interfaces/IConfig.h
src/base/kernel/interfaces/IDnsBackend.h
src/base/net/dns/Dns.cpp
src/base/net/dns/Dns.h
src/base/net/dns/DnsConfig.cpp
src/base/net/dns/DnsConfig.h
src/base/net/dns/DnsRecord.cpp
src/base/net/dns/DnsRecord.h
src/base/net/dns/DnsRecords.cpp
src/base/net/dns/DnsRecords.h
src/base/net/dns/DnsRequest.h
src/base/net/dns/DnsUvBackend.cpp
src/base/net/dns/DnsUvBackend.h
src/config.json
src/core/config/Config_platform.h
src/core/config/usage.h

The default behavior for DNS requests now treats IPv4 and IPv6 equally, with the option to prioritize one while failback to IPv4 if necessary.
Option `"ipv6"` in `"dns"` object replaced to `"ip_version"` with possible values: `4` (IPv4), `6` (IPv6), or `0` (no preference). Option `6` is not strict; if no IPv6 records are found, it will automatically fall back to IPv4. In contrast, option `4` is strict and will only use IPv4 records.
Command line option `--dns-ipv6` replaced to `-4, --ipv4` and `-6, --ipv6`.
Other improvements:
- If multiple addresses are received, they will be used sequentially, starting from a random address instead of being fully random before.
- DNS errors are cached too.

Improved IPv6 support.
